import type { Action, ChatMessage } from "@/lib/types";

export const mockActions: Action[] = [
  {
    id: "act_1",
    userId: "user_1",
    type: "variance",
    severity: "critical",
    headline: "Marketing spend 23% over budget",
    detail: "$14.2K actual vs $11.5K planned",
    driver: "Primary driver: $4.1K unplanned contractor spend in week 3",
    status: "pending",
    sourceName: "Q1_budget_vs_actual.csv",
    sourceDataSourceId: "ds_1",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000),
  },
  {
    id: "act_2",
    userId: "user_1",
    type: "variance",
    severity: "warning",
    headline: "Sales spend 14% over budget",
    detail: "$22.8K actual vs $20.0K planned",
    driver: "Overage from Q1 trade show registration fees booked late",
    status: "pending",
    sourceName: "Q1_budget_vs_actual.csv",
    sourceDataSourceId: "ds_1",
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000),
  },
  {
    id: "act_3",
    userId: "user_1",
    type: "variance",
    severity: "warning",
    headline: "Customer Support spend 12.7% over budget",
    detail: "$6.2K actual vs $5.5K planned",
    driver: "Additional part-time hire for ticket backlog in February",
    status: "pending",
    sourceName: "Q1_budget_vs_actual.csv",
    sourceDataSourceId: "ds_1",
    createdAt: new Date(Date.now() - 5 * 60 * 60 * 1000),
  },
  {
    id: "act_4",
    userId: "user_1",
    type: "recommendation",
    severity: "info",
    headline: "Revenue tracking 4% above plan",
    detail: "$52.0K actual vs $50.0K planned",
    driver: "Strong performance in enterprise segment, 2 deals closed early",
    status: "pending",
    sourceName: "Q1_budget_vs_actual.csv",
    sourceDataSourceId: "ds_1",
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000),
  },
  {
    id: "act_5",
    userId: "user_1",
    type: "anomaly",
    severity: "info",
    headline: "Engineering spend 2.2% under budget",
    detail: "$45.0K actual vs $46.0K planned",
    driver: "One contractor invoice delayed to Q2, no action needed",
    status: "pending",
    sourceName: "Q1_budget_vs_actual.csv",
    sourceDataSourceId: "ds_1",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000),
  },
];

export const mockMessages: ChatMessage[] = [
  {
    id: "msg_1",
    userId: "user_1",
    role: "user",
    content: "Why is marketing over budget this quarter?",
    timestamp: new Date(Date.now() - 10 * 60 * 1000),
  },
  {
    id: "msg_2",
    userId: "user_1",
    role: "agent",
    content:
      "Marketing exceeded Q1 budget by 23% ($14.2K actual vs $11.5K planned). The primary driver is $4.1K in unplanned contractor spend during week 3, related to the product launch campaign. The remaining $2.7K variance comes from higher-than-expected paid media costs on LinkedIn campaigns.\n\nRecommend flagging this for review with the marketing lead to align on Q2 contractor budget allocation.",
    timestamp: new Date(Date.now() - 9 * 60 * 1000),
  },
  {
    id: "msg_3",
    userId: "user_1",
    role: "user",
    content: "Can you draft a note to the marketing lead about this?",
    timestamp: new Date(Date.now() - 5 * 60 * 1000),
  },
  {
    id: "msg_4",
    userId: "user_1",
    role: "agent",
    content:
      'Subject: Q1 Marketing Budget Review \u2014 23% Variance\n\nHi [Marketing Lead],\n\nQ1 marketing came in at $14.2K against a $11.5K plan (23% over). The main driver was $4.1K in unplanned contractor costs for the product launch in week 3, plus elevated LinkedIn ad spend.\n\nCan we schedule 15 minutes to align on Q2 contractor budget? I want to make sure we have the right allocation if we\'re planning another launch push.\n\nThanks,\n[Your name]',
    timestamp: new Date(Date.now() - 4 * 60 * 1000),
  },
];
