export const SAMPLE_AGENTS = [
  {
    name: "CFO Office Agent",
    status: "active" as const,
    model: "Claude Sonnet 4.6",
    description: "Primary agent for all financial journeys — reconciliation, close, capital, ECL, liquidity, returns",
    runsToday: 47,
    avgLatency: "12.4s",
    lastRun: "3 min ago",
    skills: ["monthly-financial-close", "financial-recon", "regulatory-capital-computation", "variance-review", "ar-followup"],
    isSubAgent: false,
  },
  {
    name: "AP Automation Agent",
    status: "active" as const,
    model: "Claude Haiku 4.5",
    description: "Invoice processing, duplicate detection, PO matching",
    runsToday: 23,
    avgLatency: "4.2s",
    lastRun: "12 min ago",
    skills: ["invoice-processing", "duplicate-detection"],
    isSubAgent: true,
  },
  {
    name: "Variance Analysis Agent",
    status: "draft" as const,
    model: "Claude Sonnet 4.6",
    description: "Budget vs actuals, commentary generation, board deck support",
    runsToday: 0,
    avgLatency: "—",
    lastRun: "—",
    skills: ["variance-review", "board-deck-generation"],
    isSubAgent: true,
  },
];
