// scripts/audit-csv-parsers.ts
//
// Audit-only harness: runs each of the five shape parsers against a
// catalog of real-world CSV variations and writes a pass/fail report to
// docs/audits/. Throwaway script — no tests, no production changes.
//
// Usage: npx tsx scripts/audit-csv-parsers.ts

import { writeFileSync } from "node:fs";
import {
  SHAPES,
  BASELINES,
  ALL_VARIANTS,
  runShapeOnce,
  runMatrix,
  type Shape,
  type Outcome,
  type RunResult,
  type Cell,
} from "@/lib/csv/__fixtures__/audit-fixtures";

const OUTCOME_LABEL: Record<Outcome, string> = {
  PASS: "✓",
  PARTIAL: "~",
  FAIL_DETECT: "✗D",
  FAIL_PARSE: "✗P",
  "N/A": "–",
};

function renderMatrix(cells: Cell[]): string {
  const byVariant = new Map<string, Map<Shape, Cell>>();
  for (const c of cells) {
    if (!byVariant.has(c.variantId)) byVariant.set(c.variantId, new Map());
    byVariant.get(c.variantId)!.set(c.shape, c);
  }
  const lines: string[] = [];
  lines.push(`| Variant | Description | ${SHAPES.join(" | ")} |`);
  lines.push(`|---------|-------------|${SHAPES.map(() => "---").join("|")}|`);
  for (const variant of ALL_VARIANTS) {
    const row = byVariant.get(variant.id)!;
    const rowCells = SHAPES.map((s) => OUTCOME_LABEL[row.get(s)!.outcome]);
    lines.push(`| ${variant.id} | ${variant.description} | ${rowCells.join(" | ")} |`);
  }
  return lines.join("\n");
}

function renderPerShapeFindings(cells: Cell[]): string {
  const parts: string[] = [];
  for (const shape of SHAPES) {
    parts.push(`### ${shape}\n`);
    const shapeCells = cells.filter((c) => c.shape === shape);
    const failures = shapeCells.filter((c) => c.outcome !== "PASS" && c.outcome !== "N/A");
    if (failures.length === 0) {
      parts.push("All applicable variants PASS. No gaps.\n");
      continue;
    }
    parts.push(`Failures: ${failures.length}\n`);
    for (const f of failures) {
      parts.push(`- **${f.variantId}** (${f.outcome}) — ${f.description}. ${f.detail}`);
    }
    parts.push("");
  }
  return parts.join("\n");
}

function renderPunchList(cells: Cell[]): string {
  const failuresByShape: Record<Shape, Cell[]> = { variance: [], ar: [], gl: [], sub_ledger: [], fx: [] };
  for (const c of cells) {
    if (c.outcome === "FAIL_DETECT" || c.outcome === "FAIL_PARSE" || c.outcome === "PARTIAL") {
      failuresByShape[c.shape].push(c);
    }
  }
  const ranked = SHAPES
    .map((s) => ({ shape: s, count: failuresByShape[s].length }))
    .filter((x) => x.count > 0)
    .sort((a, b) => b.count - a.count);

  if (ranked.length === 0) return "No failures. The parsers handle every tested variant.";

  const lines: string[] = [];
  for (const { shape, count } of ranked) {
    lines.push(`- \`${shape}\`: ${count} failing variant${count === 1 ? "" : "s"} — ${
      failuresByShape[shape].map((c) => c.variantId).join(", ")
    }`);
  }
  return lines.join("\n");
}

function renderReport(cells: Cell[]): string {
  const tally: Record<Outcome, number> = { PASS: 0, PARTIAL: 0, FAIL_DETECT: 0, FAIL_PARSE: 0, "N/A": 0 };
  for (const c of cells) tally[c.outcome] += 1;
  const applicable = cells.length - tally["N/A"];
  const passRate = `${tally.PASS}/${applicable}`;

  return `# CSV Format Robustness Audit — 2026-04-23

Generated by \`scripts/audit-csv-parsers.ts\`. Re-run to regenerate.

## Summary

Ran ${ALL_VARIANTS.length} CSV variants against ${SHAPES.length} shape parsers. ${passRate} applicable (shape, variant) pairs produce output semantically equivalent to the baseline. PARTIAL: ${tally.PARTIAL}, FAIL_DETECT: ${tally.FAIL_DETECT}, FAIL_PARSE: ${tally.FAIL_PARSE}, N/A: ${tally["N/A"]}.

Cell legend: \`✓\` PASS · \`~\` PARTIAL · \`✗D\` FAIL_DETECT · \`✗P\` FAIL_PARSE · \`–\` N/A.

## Matrix

${renderMatrix(cells)}

## Per-shape findings

${renderPerShapeFindings(cells)}

## Punch-list

Shapes ordered by failing-variant count. Each listed variant is a concrete target for a future robustness fix.

${renderPunchList(cells)}

## How to interpret

- **PASS** means the parser produced output with the same row count and the same key field as the baseline (variance=account, ar=invoiceNumber, gl/sub=reference, fx=fromCurrency).
- **PARTIAL** means the parser returned output but with a different row count or key field. For most shapes this is the \`skipped[]\` array path (rows that couldn't be parsed get collected there). For FX it's a silent drop because \`fx-rates-parser.ts:16\` continues on bad rows without tracking them.
- **FAIL_DETECT** means \`detectFastPath\` returned the wrong shape for the mutated headers. The audit does not exercise the LLM fallback; in production an LLM inference would attempt recovery.
- **FAIL_PARSE** means the parser threw.
`;
}

async function main() {
  console.log("=== Baseline verification ===");
  const baselineResults: Record<Shape, RunResult> = {} as Record<Shape, RunResult>;
  for (const shape of SHAPES) {
    const result = await runShapeOnce(shape, BASELINES[shape]);
    baselineResults[shape] = result;
    const key = result.keyField ?? "(no key)";
    console.log(`  ${shape}: ${result.outcome} — ${result.rowCount} rows, first=${key}${result.error ? ` (${result.error})` : ""}`);
    if (result.outcome !== "PASS") {
      throw new Error(`Baseline for ${shape} failed: ${result.error}`);
    }
  }
  console.log("All baselines PASS.");

  console.log("\n=== Running matrix ===");
  const cells = await runMatrix(baselineResults);

  const tally: Record<Outcome, number> = { PASS: 0, PARTIAL: 0, FAIL_DETECT: 0, FAIL_PARSE: 0, "N/A": 0 };
  for (const c of cells) tally[c.outcome] += 1;
  console.log(`Total: ${cells.length} cells`);
  console.log(`  PASS:        ${tally.PASS}`);
  console.log(`  PARTIAL:     ${tally.PARTIAL}`);
  console.log(`  FAIL_DETECT: ${tally.FAIL_DETECT}`);
  console.log(`  FAIL_PARSE:  ${tally.FAIL_PARSE}`);
  console.log(`  N/A:         ${tally["N/A"]}`);

  const reportPath = "docs/audits/2026-04-23-csv-format-robustness.md";
  const report = renderReport(cells);
  writeFileSync(reportPath, report, "utf-8");
  console.log(`\nReport written to ${reportPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
